# Borrowed from https://github.com/gitpod-io/template-nix/blob/23e258d392bee430e713638de148e566a90e2b00/.gitpod.yml
image:
  file: .gitpod.Dockerfile
tasks:
  - init: >
      mkdir -p /home/gitpod/.config/nix &&
      echo 'sandbox = false' >> /home/gitpod/.config/nix/nix.conf &&
      echo 'experimental-features = nix-command flakes' >> /home/gitpod/.config/nix/nix.conf
vscode:
  extensions:
    - bbenoist.Nix
